background {
    monitor =
    path = ~/.config/hypr/Wolke.jpg
    blur_passes = 0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(33, 204, 255, 1.0)
    inner_color = rgba(20, 20, 25, 0.9)
    font_color = rgba(255, 255, 255, 1.0)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
}
