general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 900
    on-timeout = hyprlock
}

listener {
    timeout = 1800
    on-timeout = sh -c 'if [ "$(cat /sys/class/power_supply/AC/online 2>/dev/null)" = "0" ]; then systemctl suspend; fi'
}
